package com.hyungju.api.detail; 
import java.util.ArrayList; 
public class ExtraPassive{
    public int id;
    public int num;
    public String name;
    public String originalName;
    public String ruby;
    public String detail;
    public String unmodifiedDetail;
    public String type;
    public int svtId;
    public int strengthStatus;
    public int priority;
    public int condQuestId;
    public int condQuestPhase;
    public int condLv;
    public int condLimitCount;
    public String icon;
    public ArrayList<Integer> coolDown;
    public ArrayList<Object> actIndividuality;
    public Script script;
    public ArrayList<ExtraPassive> extraPassive;
    public ArrayList<Object> skillAdd;
    public ArrayList<Object> skillSvts;
    public ArrayList<Function> functions;
    public int condFriendshipRank;
    public int eventId;
    public int flag;
    public ArrayList<Object> releaseConditions;
    public int startedAt;
    public int endedAt;
}
